### ISSUE TITLE
Crate not working for me

### ISSUE THREAD

**Issue by Roba1993** [jbr/tide-testing#1]
Hi @jbr,

thank you for the really nice crate.
I struggle to use it. When I include the `use tide_testing::TideTestingExt;` trait, rust is telling me, that it is not used.
But in parallel my implementation is arguing that, put/post/get etc are not implemented for the tide::Server.

Even more strange, when I copy paste the code of this crate into my own application (and adjust the paths), everything is working fine.

Do you have an idea?

Thanks,
Robert

**Comment by jbr** [comment]
Could you include an example of how you're using it?

**Comment by Roba1993** [comment]
I use it on a own Server struct which has the TideServer as internal.
But the same error occours when I try to use it in my test....

The place where it fails is here `self.server.post(path)`, the post is not found and the include marked as not needed.

```rust 
use tide_testing::TideTestingExt;

#[derive(Debug, Clone)]
pub struct Server {
    server: tide::Server<ServerState>,
}

impl Server {
    pub fn new() -> crate::error::Result<Self> {
        let mut app = tide::with_state(ServerState { db });
        app.at("/").serve_dir("www")?;

        let mut server = Server { server: app };

        Ok(server)
    }

    pub fn test_post(self, path: &str) -> tide_testing::surf::RequestBuilder {
        self.server.post(path)
    }
}

#[derive(Debug, Clone)]
pub struct ServerState {
    db: crate::dbal::Dbal,
}
```

**Comment by jbr** [comment]
This is not how tide testing is intended to be used, so it's unsurprising that it doesn't work. You should build your own surf::Client::with_http_client(app) for whatever this use case is, or use http_client directly. This crate is for testing tide applications.
