### ISSUE TITLE
Compatibility with tide 0.15

### ISSUE THREAD

**Issue by grasegger** [jbr/tide-testing#2]
Hi there,

I just started writing a tide app, with v0.15. The examples of tide-testing don't work anymore with that version, when I switch back to tide 0.14 the tests run fine. 

Sadly I have no clue how to fix this, so I can only ask for help and not provide a PR. 

Is there a new version planned for 0.15?

# Source
```rust
pub fn get() -> Result<String, tide::Error> { 
    Ok("Hello world!".to_string())
}


#[cfg(test)] 
mod test {
    use super::get;
    use std::assert_eq;
    use futures_await_test::async_test;

    #[async_test]
    pub async fn get_test() {
        let mut app = tide::new();
        app.at("/").get(|_| async { get() });

        use tide_testing::TideTestingExt;
        assert_eq!(
            app.get("/").recv_string().await.unwrap(),
            "Hello world!"
        )
    }
}
```

# Error
```
   |
19 |             app.get("/").recv_string().await.unwrap(),
   |                 ^^^ method not found in `Server<()>`
```

**Comment by jbr** [comment]
Thanks for this! We didn't communicate well internally about tide 0.15 so some of my crates lagged behind. Just released tide-testing 0.1.2 — you should be able to `cargo update` in your tide 0.15 app
